sbernauer/breakwater

Cargo.lock
Cargo.toml
benches/benchmarks.rs
src/test/helpers/pixelflut_commands.rs

The current implementation takes a significant hit from a random load, as it turns out that the branch predictor is pretty good at predicting predictable stuff.
(11ms vs 19ms on my machine)

new bench that tests random command ordering, to confuse the branch predictor

---

src/parser.rs

CC @fabi321 
```
parse_draw_commands_ordered/1920 x 1080
time:   [25.165 ms 25.224 ms 25.285 ms]
change: [-2.5271% -0.9256% +0.1508%] (p = 0.22 > 0.05)
No change in performance detected.
parse_draw_commands_shuffled/1920 x 1080
time:   [31.482 ms 31.761 ms 32.174 ms]
change: [-4.3100% -3.1584% -1.6421%] (p = 0.00 < 0.05)
Performance has improved.
Found 7 outliers among 100 measurements (7.00%)
1 (1.00%) low mild
2 (2.00%) high mild
4 (4.00%) high severe
```

feat: Improve coordinate parsing (no SIMD)

---

src/parser.rs

Will be optimized to basically the same assembler, but better to read. The performance difference is within the noise threshold for me.

rewrote the digit parsing to be more readable

---

src/main.rs
src/sinks/ffmpeg.rs
src/sinks/vnc.rs

A small step for this repo, a big step for https://github.com/sbernauer/breakwater/issues/6

fix: Signal handling

---

src/network.rs
src/parser.rs

due to one side containing a space, but the mask eliding the space, OFFSET never matched

fix offset parsing

---

src/parser.rs

This nets me 2.5% - 6% improvement depending on the benchmark

removing bounds checking

---

README.md
breakwater/src/server.rs

Reported in https://github.com/sbernauer/breakwater/issues/28
Also reduce the severity to warning as everything should continue working
CC @robinchrist

docs: Document know issue of failing memadvise

---

Cargo.lock
breakwater-parser/Cargo.toml
breakwater-parser/benches/parsing.rs
breakwater-parser/src/assembler.rs
breakwater-parser/src/lib.rs
breakwater-parser/src/memchr.rs
breakwater-parser/src/original.rs
breakwater-parser/src/refactored.rs
breakwater/src/server.rs

This **should** also improve performance for write only traffic (which is 99% of the traffic) as we can remove the overhead of async and error handling.
We (@fabi321, @bits0rcerer and @sbernauer) tested the performance during GPN22 and come to the following measurements:
| Hardware           | before | after |
|--------------------|--------|-------|
| @sbernauer Laptop  | 16G    | 21G   |
| @fabi321s Laptop    | 26G    | 28G   |
| @bits0rcerer Laptop | 78G    | 82G   |
| 80 core Ampere server (arm) | 420G | 407G |
So to sum it up it's faster on all x86 machines, but somehow slower on the big arm server. I really don't know how removing async and error-handling make thing slower but I guess the x86 speedup is more important.

refactor: Simplify Parse trait by using Vec<u8> instead of AyncWriteExt

---

CHANGELOG.md
breakwater/src/main.rs

From
`Error: StartVncServer { source: ReadFontFile { source: Os { code: 2, kind: NotFound, message: "No such file or directory" }, font_file: "212" } }`
to
```
Error: Failed to start VNC server
Caused by these errors (recent errors listed first):
1: Failed to read font from file 212
2: No such file or directory (os error 2)
```

feat: Print nicer error messages

---

breakwater-parser/src/original.rs

This PR fixes:
- an off by two error in the original parser while parsing `HELP` and `SIZE` commands. (I think this should save 2 loop iterations in the parser loop)
- set `last_byte_parsed` for the binary `PB` command

Original parser fixes

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
breakwater/Cargo.toml
breakwater/src/cli_args.rs
breakwater/src/main.rs
breakwater/src/sinks/ffmpeg.rs
breakwater/src/sinks/mod.rs
breakwater/src/sinks/native_display.rs
breakwater/src/sinks/vnc.rs
breakwater/src/statistics.rs
default.nix

1. Put DisplaySinks behind a shared trait `DisplaySink`, so far we have native display, VNC and ffmpeg
2. Add native display sink
This feature was inspired by https://github.com/Rairosu/breakwater/tree/display_sink, so many thanks @Rairosu!
Co-authored-by: Rairosu <b.boll@avolens.com>

feat!: Add native display sink

---

breakwater-parser/src/original.rs
breakwater-parser/src/refactored.rs
breakwater/src/server.rs
breakwater/src/sinks/vnc.rs

Fixes all warnings with clippy `1.85.0-nightly`

chore: Fix clippy warnings

---

breakwater/src/sinks/native_display.rs

winit+x11 usually supplies a single redraw event where the window’s backing buffer is still size zero. ignoring this case stops the event handler thread from panicking.
physical size is needed since our raw framebuffer work doesn’t care about logical pixels and associated DPI scaling. with logical size, the window is too large (or even too small) for the area that is actually used for the framebuffer.

fix: two fixes around native display output

---

CHANGELOG.md
Cargo.lock
Cargo.toml
docker/docker-compose.yml

- Ignore spurious zero-sized window buffers in native display sink ([#42])
- Use physical size for winit window in native display sink ([#42])

Release 0.16.2

---

CHANGELOG.md
README.md
breakwater/src/connection_buffer.rs
breakwater/src/main.rs
breakwater/src/server.rs
breakwater/src/tests.rs

This PR fixes a memory leak that occurred because we did not deallocate the rx buffers of our connection. This PR introduces a new struct handling the allocation and deallocation.
Closer inspection revealed a potential cause for #28.
`alloc::alloc()` returns a null pointer in case of error. This PR now handles that. [docs](https://doc.rust-lang.org/alloc/alloc/trait.GlobalAlloc.html#errors)

fix: Fix memory leak for receive buffers

---

CHANGELOG.md
Cargo.lock
Cargo.toml
docker/docker-compose.yml

- Receive buffers for pixelflut connections that were leaked before will now be properly deallocated ([#46])
- Errors while allocating receive buffers for pixelflut connections are now handled properly ([#46])
[#46]: https://github.com/sbernauer/breakwater/pull/46

chore: Release 0.16.3

---

CHANGELOG.md
breakwater/src/main.rs
breakwater/src/statistics.rs

In https://github.com/sbernauer/breakwater/pull/48 we noticed that we did not send statistic information updates periodically in case no stats are send.
This PR fixes this and ensures statistic information updates are send periodically.

fix: Ensure stat information updates are send periodically

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
breakwater-egui-overlay/Cargo.toml
breakwater-egui-overlay/build.rs
breakwater-egui-overlay/src/lib.rs
breakwater-parser/Cargo.toml
breakwater/Cargo.toml
breakwater/src/cli_args.rs
breakwater/src/main.rs
breakwater/src/sinks/egui/canvas.frag
breakwater/src/sinks/egui/canvas.vert
breakwater/src/sinks/egui/canvas_renderer.rs
breakwater/src/sinks/egui/dynamic_overlay.rs
breakwater/src/sinks/egui/mod.rs
breakwater/src/sinks/egui/view.rs
breakwater/src/sinks/mod.rs
docs/custom-overlay.md

This PR introduces a new type of DisplaySink as an alternative to the current native display.
The new native display:
- can open multiple windows that may show different/overlapping/same parts of the pixelflut canvas
- has predictable names for its windows which helps binding them to outputs in your favorite window manager
- comes with a builtin overlay on the first viewport featuring basic stats, information
- can load custom third-party overlays from dynamic shared libraries. [example](https://github.com/bits0rcerer/breakwater-38c3-overlay)

feat: Add egui and eframe for native display and nice ui

---

CHANGELOG.md
breakwater-parser/benches/parsing.rs
breakwater-parser/src/framebuffer/shared_memory.rs
breakwater/src/tests.rs

Tests would have catched it :rocket: 
But we haven't switched the tests to the new `SharedMemoryFrameBuffer` yet :upside_down_face:

fix: Wrong PXMULTI handling

---

CHANGELOG.md
breakwater-parser/src/framebuffer/shared_memory.rs

It now only warns when the shared memory is too big.
This e.g. might be the case when pixelflut-v6 crates the shared memory, as it also has statistics bytes after the framebuffer.

chore: Relax shared memory size check
